### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Ariel-Berkowicz** [McLovinCSUN/SecondChance#8]
Create simple footer that actually looks professional.

**Comment by Ariel-Berkowicz** [comment]
https://website329902.nicepage.io/Home.html

**Comment by McLovinCSUN** [comment]
the footer should contain 2 columns
1st column address to CSUN with an icon. clicking on the address doesn't do anything
address to use: 
Project Rebound
CHS JR Hall 148
18111 Nordhoff Street
Northridge, CA 91330-8246
2nd email address: projectrebound@csun.edu clicking on the email will open up a new email. alternatively, if this takes longer than one day we can set it to clicking on the email was copied onto the clipboard and have a floating text stating copied

**Comment by McLovinCSUN** [comment]
update version of the home page with the footer
https://website329902.nicepage.io/Home.html?version=617af214-52c4-4bdb-b1fc-30936d13107a&uid=07f4ab92-817d-4d02-b039-a3629cd71258
